### ISSUE TITLE
Standardized checks

### ISSUE THREAD

**Issue by dsmedia** [vega/vega-datasets#685]
The `vega-datasets` repository currently lacks a straightforward, documented way to run code quality checks locally that match CI checks (`.github/workflows/test.yml`). This diverges from projects like Altair (@dangotbanned) that use `uv` and `taskipy` for an efficient developer workflow. Such an approach paves the way for a very user-friendly [CONTRIBUTING.md](https://github.com/vega/altair/blob/main/CONTRIBUTING.md) in Altair. 

## Current Situation
Currently, developers can run each CI check manually using separate commands:
```bash
# TOML formatting check
uvx taplo fmt --check --diff
# Python linting
uvx ruff check
# Python formatting check
uvx ruff format --check
```
While this works, it's cumbersome to run multiple commands and inconsistent with related projects like Altair that provide a single command for all checks. There's no documented way to run all checks with one command.

### Option 1: Shell Script
A simple, direct approach:

1. Create `run_checks.sh`:
```bash
#!/bin/bash
set -e
uvx taplo fmt --check --diff
uvx ruff check
uvx ruff format --check
echo "All checks passed!"
```

2. Usage: `./run_checks.sh`

**Advantages:**
- No additional dependencies needed
- Simple to understand and maintain
- Directly mirrors CI commands
- Quick to implement
- Easy to modify or extend

### Option 2: Full `taskipy` Implementation
Adopt an Altair-like `taskipy` setup for better structure and extensibility:

1. Add to `pyproject.toml` dependency groups:
```toml
[dependency-groups]
dev = ["taskipy>=1.14.1"]
```

2. Define individual tasks:
```toml
[tool.taskipy.tasks]
check-toml = "taplo fmt --check --diff"
check-lint = "ruff check"
check-format = "ruff format --check"
checks = "task check-toml && task check-lint && task check-format"
```

3. Usage: `uv run task checks`

**Advantages:**
- Structured approach matching Altair
- Centralized task definitions
- Extensible for future additions
- Familiar interface for Altair contributors (`uv run task ...`)

**Disadvantages:**
- Slightly more complex initial setup (though minimal)

What approach would work best?
